const $=id=>document.getElementById(id);
let registerMode=false,currentStory=null;
async function api(url,options={}){const r=await fetch(url,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});const d=await r.json();if(!r.ok||d.success===false)throw new Error(d.message||"Request failed");return d}
function show(id){["auth","creator","saved"].forEach(x=>$(x).classList.toggle("hidden",x!==id))}
function authMode(reg){registerMode=reg;$("loginTab").classList.toggle("active",!reg);$("registerTab").classList.toggle("active",reg);$("authSubmit").textContent=reg?"Create account":"Login";$("authMsg").textContent=""}
$("loginTab").onclick=()=>authMode(false);$("registerTab").onclick=()=>authMode(true);
$("authForm").onsubmit=async e=>{e.preventDefault();$("authMsg").textContent="Please wait...";try{const d=await api(registerMode?"/api/register":"/api/login",{method:"POST",body:JSON.stringify({username:$("username").value,password:$("password").value})});enter(d.username)}catch(err){$("authMsg").textContent=err.message}};
function enter(name){$("who").textContent=`Hi, ${name}`;$("logout").classList.remove("hidden");$("savedNav").classList.remove("hidden");show("creator")}
async function check(){try{const d=await api("/api/me");if(d.user)enter(d.user.username)}catch{}}
$("logout").onclick=async()=>{await api("/api/logout",{method:"POST"});$("who").textContent="";$("logout").classList.add("hidden");$("savedNav").classList.add("hidden");show("auth")};
$("generate").onclick=async()=>{const idea=$("idea").value.trim();if(!idea){$("status").textContent="Please enter a story idea.";return}$("generate").disabled=true;$("status").textContent="Creating your story...";try{const d=await api("/api/generate",{method:"POST",body:JSON.stringify({idea,genre:$("genre").value,count:Number($("count").value)})});currentStory=d.story;render(currentStory);$("status").textContent=d.notice||"Story ready!";}catch(e){$("status").textContent=e.message}finally{$("generate").disabled=false}};
function render(s){$("title").textContent=s.title;$("summary").textContent=s.summary;$("characters").innerHTML="";(s.characters||[]).forEach(c=>{const li=document.createElement("li");li.textContent=c;$("characters").append(li)});$("panels").innerHTML="";(s.panels||[]).forEach((p,i)=>{const el=document.createElement("article");el.className="panel";const art=document.createElement("div");art.className="art";art.textContent=["🎨","🌟","🚀","🗺️"][i%4];const body=document.createElement("div");body.className="panelbody";const h=document.createElement("h3");h.textContent=`Panel ${p.number||i+1}`;const scene=document.createElement("p");scene.textContent="Scene: "+p.scene;const dialog=document.createElement("p");dialog.textContent="Dialogue: "+p.dialogue;body.append(h,scene,dialog);el.append(art,body);$("panels").append(el)});$("result").classList.remove("hidden")}
$("save").onclick=async()=>{if(!currentStory)return;try{await api("/api/comics",{method:"POST",body:JSON.stringify(currentStory)});$("status").textContent="Comic saved to your account!";}catch(e){$("status").textContent=e.message}};
$("pdf").onclick=()=>window.print();
async function loadSaved(){show("saved");$("savedList").textContent="Loading...";try{const d=await api("/api/comics");$("savedList").innerHTML="";if(!d.comics.length){$("savedList").textContent="No saved comics yet.";return}d.comics.forEach(c=>{const el=document.createElement("div");el.className="savedcard";const h=document.createElement("h3");h.textContent=c.title;const p=document.createElement("p");p.textContent=c.summary;const b=document.createElement("button");b.className="ghost";b.textContent="Delete";b.onclick=async()=>{if(confirm("Delete this comic?")){await api("/api/comics/"+c.id,{method:"DELETE"});loadSaved()}};el.append(h,p,b);$("savedList").append(el)})}catch(e){$("savedList").textContent=e.message}}
$("savedNav").onclick=loadSaved;$("back").onclick=()=>show("creator");check();